DROP TABLE users IF EXISTS;
CREATE TABLE users (
  userid bigint generated by default as identity (start with 1, increment by 1) not null,
  username varchar(50) NOT NULL,
  countrycode varchar(5) NOT NULL,
  phonenumber varchar(10) NOT NULL,
  email varchar(50) NOT NULL,
  reg_date TIMESTAMP DEFAULT NULL,
  passwd varchar(100) DEFAULT NULL,
  PRIMARY KEY (userid)
);
